Repository wanted-wecode-subjects/deer-subject, pull requests merged in 2021-11, with the labels that each got.

#10 chore: 프로젝트 생성
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/entities/area.entity.ts
  src/entities/deer.entity.ts
  src/entities/forbidden_area.entity.ts
  src/entities/history.entity.ts
  src/entities/parkingzone.entity.ts
  src/entities/user.entity.ts
  src/main.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: chore

#14 feat: 회원가입 구현
  package-lock.json
  src/app.module.ts
  src/entities/user.entity.ts
  src/user/dto/create-user.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: feat

#16 feat : 히스토리 초기 세팅
  package-lock.json
  src/app.module.ts
  src/history/history.controller.ts
  src/history/history.module.ts
  src/history/history.repository.ts
  src/history/history.service.ts
Labels: feat

#18 feat: user signin
  package-lock.json
  package.json
  src/auth/auth-guard/jwt-auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/get-user.decorator.ts
  src/auth/strategies/jwt.strategy.ts
  src/entities/user.entity.ts
  src/user/dto/sign-in.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: feat

#17 feat: 대여 개발
  src/app.module.ts
  src/deer/deer.module.ts
  src/deer/deer.service.ts
  src/entities/deer.entity.ts
  src/entities/history.entity.ts
  src/history/dto/create-history.dto.ts
  src/history/history.controller.ts
  src/history/history.module.ts
  src/history/history.service.ts
Labels: feat

#19 feat: 이용 내역 리스트 조회
  src/history/dto/query-history.dto.ts
  src/history/history.controller.ts
  src/history/history.service.ts
Labels: feat

#20 refactor: update, delete 코드 삭제
  src/user/dto/update-user.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: refactor

#23 feat: 반납
  src/entities/area.entity.ts
  src/entities/deer.entity.ts
  src/entities/history.entity.ts
  src/history/dto/update-history.dto.ts
  src/history/history.controller.ts
  src/history/history.repository.ts
  src/history/history.service.ts
Labels: feat

#22 test: user service unit test 작성
  src/user/user.service.spec.ts
  src/user/user.service.ts
Labels: test

#28 feat: 이벤트 추가 기능
  src/entities/event.entity.ts
  src/event/dto/create-event.dto.ts
  src/event/event.service.ts
Labels: feat

#31 feat: 이벤트 리스트 조회
  src/event/event.controller.ts
  src/event/event.service.ts
Labels: feat

#32 feat: 이벤트 수정
  src/event/dto/update-event.dto.ts
  src/event/event.controller.ts
  src/event/event.service.ts
Labels: feat

#33 feat: 이벤트의 조건을 검증하는 checkConditionValidate 메소드 작성
  src/event/event.service.ts
Labels: feat

#34 feat : 이벤트 생성 검증 연결
  src/event/event.service.ts
Labels: feat

#38 chore: 배포 파일 추가
  Procfile
Labels: chore

#36 docs: 리드미 파일 수정
  README.md
Labels: documentation
